In [1]:
import numpy as np
import gym
import time
import random
from IPython.display import clear_output

In [2]:
env=gym.make('FrozenLake-v1')

In [3]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n

q_table=np.zeros((state_space_size,action_space_size))
q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Parameters

In [4]:
num_episodes=10000
max_steps=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration=1
min_exploration=0.01
exploration_decay=0.001  # test this parameter and compare results

In [5]:
rewards=[]

for episode in range(num_episodes):
    state=env.reset()[0]
    done=False
    rewards_current=0
    for step in range(max_steps):
        exp_threshold=random.uniform(0,1)
        if exp_threshold > exploration_rate:
            action=np.argmax(q_table[state,:])
        else:
            action=env.action_space.sample()

        new_state,reward,done,truncated,info=env.step(action)

        #update q-table
        q_table[state,action]=(1-learning_rate)*q_table[state,action] +\
        learning_rate * (reward + discount_rate*np.max(q_table[new_state,:])) 

        state=new_state
        rewards_current+=reward

        if done:
            break
    exploration_rate=exploration_rate - exploration_rate*exploration_decay
    rewards.append(rewards_current)  

C:\Users\kaan\anaconda3\envs\q-learning\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


In [6]:
rewards_per_thousand=np.split(np.array(rewards),num_episodes/1000)
count=1000
print("*************results*************\n")
for r in rewards_per_thousand:
    print(count,": ",str(sum(r/1000)))
    count+=1000
print()
print(q_table)


*************results*************

1000 :  0.046000000000000034
2000 :  0.20000000000000015
3000 :  0.4100000000000003
4000 :  0.5940000000000004
5000 :  0.6830000000000005
6000 :  0.7210000000000005
7000 :  0.7200000000000005
8000 :  0.7400000000000005
9000 :  0.7340000000000005
10000 :  0.7410000000000005

[[0.59557832 0.47034692 0.47020976 0.47130197]
 [0.36059332 0.30538498 0.33102673 0.51744728]
 [0.41804179 0.41607337 0.41582565 0.47947779]
 [0.25668466 0.23652283 0.25330965 0.47104342]
 [0.61851793 0.43951005 0.33613513 0.36234665]
 [0.         0.         0.         0.        ]
 [0.26955487 0.1720474  0.17691801 0.1613953 ]
 [0.         0.         0.         0.        ]
 [0.32413929 0.43232169 0.37638358 0.67541907]
 [0.47534548 0.75269973 0.52920338 0.43580492]
 [0.71889081 0.39650518 0.34171977 0.26016616]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.5101649  0.6112296  0.80708625 0.55936969]
 [0.68450955 0.90589746 0.724487